### ISSUE TITLE
How is this different from GPSToggler?

### ISSUE THREAD

**Issue by ber4444** [sms2000/GPSTogglerM#1]
The essence of the difference seems to be:

```
      if (android.os.Build.VERSION.SDK_INT >= Build.VERSION_CODES.KITKAT) {
            Settings.Secure.putInt (mContentResolver,
                             Settings.Secure.LOCATION_MODE,
                             Settings.Secure.LOCATION_MODE_HIGH_ACCURACY);
    } else {
          String beforeEnable = Settings.Secure.getString(mContentResolver, Settings.Secure.LOCATION_PROVIDERS_ALLOWED);
          String newSet = String.format("%s,%s", beforeEnable, LocationManager.GPS_PROVIDER);
          Settings.Secure.putString(mContentResolver,
                               Settings.Secure.LOCATION_PROVIDERS_ALLOWED,
                               newSet);
  }
```

but there must be something more to it which I can't identify. 
One thing is that I don't copy to the system directory and don't do reboot. It was not necessary on a rooted Android 5 with my code (but you do it even in the legacy GPSToggler). However, my code does not work on Android 6 and your project works on Android 6 too, that's why I'm asking what makes the difference.

**Comment by ber4444** [comment]
I also don't understand how WRITE_SECURE_SETTINGS gets granted on Android 6 as it has a runtime permission model and this permission cannot be requested runtime. Maybe that's why the app needs to go to the system directory?

**Comment by sms2000** [comment]
Hi

The application must be System application to use WRITE_SECURE_SETTINGS. 

And only /system/priv-app/ located apps are the System apps. 

Be Android design only the System apps may turn the GPS on/off.

Yours

Sergey

**Comment by sms2000** [comment]
The application must be System application to use WRITE_SECURE_SETTINGS. 
And only /system/priv-app/ located apps are the System apps. 

Be Android design only the System apps may turn the GPS on/off. No exceptions.

**Comment by ber4444** [comment]
Thanks man, it works now.
